"""Accuracy and Relevance Assessment framework.

Evaluates generated outputs against ground truth baselines to ensure
system reliability and data accuracy.
"""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from litellm import completion
from config.settings import settings
from src.utils import read_prompt

logger = logging.getLogger(__name__)


@dataclass
class AssessmentResult:
    """Result of a single assessment evaluation."""

    query: str
    expected_answer: str
    actual_answer: str
    agent_used: str

    factual_accuracy: float = 0.0
    completeness: float = 0.0
    consistency: float = 0.0
    overall_score: float = 0.0
    feedback: str = ""

    def passed(self, threshold: float = 0.7) -> bool:
        return self.overall_score >= threshold


@dataclass
class AssessmentReport:
    """Aggregate assessment report across multiple evaluations."""

    results: list[AssessmentResult] = field(default_factory=list)

    @property
    def average_accuracy(self) -> float:
        if not self.results:
            return 0.0
        return sum(r.factual_accuracy for r in self.results) / len(self.results)

    @property
    def average_completeness(self) -> float:
        if not self.results:
            return 0.0
        return sum(r.completeness for r in self.results) / len(self.results)

    @property
    def average_consistency(self) -> float:
        if not self.results:
            return 0.0
        return sum(r.consistency for r in self.results) / len(self.results)

    def pass_rate(self, threshold: float = 0.7) -> float:
        if not self.results:
            return 0.0
        passed = sum(1 for r in self.results if r.passed(threshold))
        return passed / len(self.results)

    def summary(self, threshold: float = 0.7) -> str:
        lines = [
            "Assessment Report",
            "=" * 40,
            f"Total evaluations: {len(self.results)}",
            f"Pass rate (threshold {threshold}): {self.pass_rate(threshold):.0%}",
            f"Average factual accuracy: {self.average_accuracy:.2f}",
            f"Average completeness: {self.average_completeness:.2f}",
            f"Average consistency: {self.average_consistency:.2f}",
        ]

        failed = [r for r in self.results if not r.passed()]
        if failed:
            lines.append(f"\nFailed evaluations ({len(failed)}):")
            for r in failed:
                lines.append(f"  - Query: {r.query[:60]}...")
                lines.append(f"    Score: {r.overall_score:.2f} | Feedback: {r.feedback[:80]}")

        return "\n".join(lines)


def assess_response(
    query: str,
    expected_answer: str,
    actual_answer: str,
    agent_used: str = "general",
) -> AssessmentResult:
    """Evaluate a generated response against an expected answer using an LLM judge.

    Scores each dimension from 0.0 to 1.0:
    - factual_accuracy: Are the facts in the actual answer correct?
    - completeness: Does the actual answer cover all key points?
    - consistency: Is the actual answer internally consistent and non-contradictory?

    Args:
        query: The original user query
        expected_answer: The ground truth / expected answer
        actual_answer: The answer generated by the system
        agent_used: Which sub-agent generated the answer

    Returns:
        AssessmentResult with scores and feedback
    """
    judge_prompt = """You are an impartial evaluator assessing the quality of financial analysis responses.

Evaluate the actual answer against the expected answer on three dimensions (0.0 to 1.0):

1. factual_accuracy: Are the numerical facts, company names, and data points correct?
2. completeness: Does the answer cover all the key points from the expected answer?
3. consistency: Is the answer internally consistent without contradictions?

Return ONLY a JSON object with this structure:
{
  "factual_accuracy": 0.0-1.0,
  "completeness": 0.0-1.0,
  "consistency": 0.0-1.0,
  "overall_score": 0.0-1.0,
  "feedback": "Brief explanation of the scores"
}

Do not include any text outside the JSON."""

    messages = [
        {"role": "system", "content": judge_prompt},
        {"role": "user", "content": f"Query: {query}\n\nExpected: {expected_answer}\n\nActual: {actual_answer}"},
    ]

    try:
        response = completion(
            model=settings.high_capacity_llm_model,
            messages=messages,
            api_key=settings.high_capacity_llm_api_key or None,
            api_base=getattr(settings, "high_capacity_llm_api_base", None) or None,
            temperature=0.0,
            max_tokens=512,
        )

        result_text = response.choices[0].message.content.strip()
        parts = result_text.split("```")
        if len(parts) > 1:
            result_text = parts[1]
            if result_text.startswith("json"):
                result_text = result_text[4:]
        result_text = result_text.strip()

        scores = json.loads(result_text)

        result = AssessmentResult(
            query=query,
            expected_answer=expected_answer,
            actual_answer=actual_answer,
            agent_used=agent_used,
            factual_accuracy=float(scores.get("factual_accuracy", 0)),
            completeness=float(scores.get("completeness", 0)),
            consistency=float(scores.get("consistency", 0)),
            overall_score=float(scores.get("overall_score", 0)),
            feedback=scores.get("feedback", ""),
        )

        logger.info(f"Assessment: {result.overall_score:.2f} for query: {query[:50]}")
        return result

    except Exception as e:
        logger.error(f"Assessment failed: {e}")
        return AssessmentResult(
            query=query,
            expected_answer=expected_answer,
            actual_answer=actual_answer,
            agent_used=agent_used,
            feedback=f"Assessment error: {e}",
        )


def run_assessment_suite(test_cases: list[dict]) -> AssessmentReport:
    """Run a batch of assessments and generate a report.

    Each test case is a dict with:
    - query: The user query
    - expected_answer: The ground truth answer
    - actual_answer: The system-generated answer (or will be generated)
    - agent_used: (optional) Which agent was used

    Args:
        test_cases: List of test case dicts

    Returns:
        AssessmentReport with all results
    """
    report = AssessmentReport()

    for case in test_cases:
        result = assess_response(
            query=case["query"],
            expected_answer=case["expected_answer"],
            actual_answer=case.get("actual_answer", ""),
            agent_used=case.get("agent_used", "general"),
        )
        report.results.append(result)

    return report


def save_report(report: AssessmentReport, output_path: Path) -> None:
    """Save an assessment report to a JSON file."""
    data = {
        "summary": {
            "total_evaluations": len(report.results),
            "pass_rate": report.pass_rate(),
            "average_accuracy": report.average_accuracy,
            "average_completeness": report.average_completeness,
            "average_consistency": report.average_consistency,
        },
        "results": [
            {
                "query": r.query,
                "expected_answer": r.expected_answer,
                "actual_answer": r.actual_answer,
                "agent_used": r.agent_used,
                "factual_accuracy": r.factual_accuracy,
                "completeness": r.completeness,
                "consistency": r.consistency,
                "overall_score": r.overall_score,
                "feedback": r.feedback,
                "passed": r.passed(),
            }
            for r in report.results
        ],
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    logger.info(f"Assessment report saved to {output_path}")
